pragma Singleton

import QtQuick

QtObject {
    readonly property string alarmClock: "󰔛"
    readonly property string bell: "󰂚"
    readonly property string bellOff: "󰂛"
    readonly property string bluetooth: "󰂯"
    readonly property string check: "󰄬"
    readonly property string chevronLeft: "󰅁"
    readonly property string chevronRight: "󰅂"
    readonly property string circleAlert: "󰅚"
    readonly property string close: "󰅖"
    readonly property string computer: "󰍹"
    readonly property string cpu: ""
    readonly property string ellipsis: "󰇘"
    readonly property string emoji: "󰞅"
    readonly property string home: "󰋜"
    readonly property string lock: "󰌾"
    readonly property string logOut: "󰍃"
    readonly property string memory: ""
    readonly property string microphone: "󰍬"
    readonly property string microphoneOff: "󰍭"
    readonly property string moon: "󰖔"
    readonly property string music: "󰎆"
    readonly property string packageIcon: "󰏔"
    readonly property string pause: "󰏤"
    readonly property string play: "󰐊"
    readonly property string power: "󰐥"
    readonly property string refresh: "󰑐"
    readonly property string searchOff: "󰍉"
    readonly property string settings: "󰒓"
    readonly property string skipBack: "󰒮"
    readonly property string skipForward: "󰒭"
    readonly property string snowflake: "󰜗"
    readonly property string success: "󰄬"
    readonly property string sun: "󰖙"
    readonly property string warning: "󰀪"
    readonly property string volumeHigh: "󰕾"
    readonly property string volumeLow: "󰕿"
    readonly property string volumeOff: "󰝟"
    readonly property string wifi: "󰖩"
}
